apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-social
  namespace: default
spec:
  releaseName: postgres-social
  targetNamespace: social
  chart:
    spec:
      chart: postgresql
      version: 11.0.x
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
  interval: '1m0s'
  install:
    remediation:
      retries: 3
    timeout: '10m0s'
  # https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values
  values:
    image:
      registry: docker.io
      repository: postgres
      tag: 12.11
    global:
      postgresql:
        auth:
          username: social-api
          database: social-db
          existingSecret: postgres-social-secret
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: password
            replicationPasswordKey: replication-password
    volumePermissions:
      enabled: true
    primary:
      persistence:
        enabled: true
        accessModes:
        - ReadWriteOnce
        size: 8Gi
      resources:
        limits:
          memory: 256Mi
          cpu: 250m
        requests:
          memory: 256Mi
          cpu: 250m
