apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: auth-stack-dev
  namespace: auth
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: keycloak-secret
  namespace: auth
  envs:
  - secrets/keycloak.env
- name: pg-keycloak
  namespace: auth
  envs:
  - secrets/pg-keycloak.env
resources:
  - namespace.yaml
  - ingress-route.yaml
  - ../../base/auth
patchesStrategicMerge:
  - auth-patch.yaml