apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-gitter-cert
  namespace: kube-system
spec:
  secretName: dev-cert-secret
  issuerRef:
    name: gitter-dev
    kind: ClusterIssuer
  dnsNames:
    - "dev.gitter.uk"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "auth,kube-system,bucket-service,social"  
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "auth,kube-system,bucket-service,social"