apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gitter-dev
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: paul.barrie.calmels@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: issuer-cert-secret
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudflare:
          email: paul.barrie.calmels@gmail.com
          apiKeySecretRef:
            name: cloudflare-secret
            key: api-key