apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitter-app
  namespace: app-service
  labels:
    app: gitter-app
spec:
  selector:
    matchLabels:
      app: gitter-app
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: gitter-app
    spec:
      containers:
      - name: gitter-app
        image: quay.io/gitter/gitter-app:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gitter-app
  namespace: app-service
spec:
  selector:
    app: gitter-app
  ports:
  - port: 3000
    targetPort: 80
