apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-stack-dev
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: cloudflare-secret
  namespace: kube-system
  envs:
  - secrets/cloudflare-secret.env
resources:
  - cluster-issuer.yaml
  - certificate.yaml