apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-api
  namespace: code-service
spec:
  selector:
    matchLabels:
      app: code-api
  replicas: 3
  rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: code-api
    spec:
      containers:
      - name: code-api
        image: quay.io/gitter/gitter-code-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        env:
        - name: OPENFAAS_URL
          value: http://gateway:8080/
        - name: OPENFAAS_USERNAME
          valueFrom:
            secretKeyRef:
              name: basic-auth
              key: basic-auth-user
        - name: OPENFAAS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-auth
              key: basic-auth-password
        - name: MINIO_HOST
          value: minio-release.bucket-service.svc.cluster.local
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: code-api
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: code-api
              key: minio-access-secret
        - name: MINIO_BUCKET
          valueFrom:
            secretKeyRef:
              name: code-api
              key: minio-bucket

---
apiVersion: v1
kind: Service
metadata:
  name: code-api
  namespace: code-service
spec:
  selector:
    app: code-api
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
