#Source: https://artifacthub.io/packages/helm/openfaas/openfaas
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openfaas-stack
resources:
  - openfaas-release.yaml
  - code-api-deployment.yaml
