apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: kube-system
spec:
  releaseName: cert-manager
  targetNamespace: kube-system
  chart:
    spec:
      chart: cert-manager
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: jetstack-repo
        namespace: flux-system
  interval: '1m0s'
  install:
    remediation:
      retries: 3
    timeout: '10m0s'
  values:
    installCRDs: true
    replicaCount: 1
    clusterResourceNamespace: kube-system