apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: auth-stack-dev
  namespace: kube-system
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base/traefik-ingress
  - ingress-route.yaml
patchesStrategicMerge:
  - traefik-release-patch.yaml