#Source: https://artifacthub.io/packages/helm/openfaas/openfaas
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openfaas-stack-dev
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: basic-auth
  namespace: openfaas
  envs:
  - secrets/basic-auth.env
resources:
  - namespaces.yaml
  - ../../base/openfaas
  - ingress-route.yaml
patchesStrategicMerge:
  - openfaas-release-patch.yaml
