apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: auth-stack-prod
  namespace: auth
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: keycloak-secret
  namespace: auth
  envs:
  - secrets/keycloak.env
- name: keycloak-postgresql
  namespace: auth
  envs:
  - secrets/pg-keycloak.env
- name: realm-secret
  namespace: auth
  files:
  - secrets/realm-config.json

resources:
  - namespace.yaml
  - ../../base/auth
  - ingress-route.yaml
